server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Esta línea redirige todas las rutas no encontradas al index.html de React
        try_files $uri $uri/ /index.html;
    }
}